[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"

domain = { path = "../domain" }