services:
  poc-rocket-db:
    image: postgres:14
    container_name: poc-rocket-db
    ports:
      - "5432:5432"
    volumes:
      - poc-rocket-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=poc-rocket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

volumes:
  poc-rocket-data: