[package]
name = "presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.6", features = ["postgres", "r2d2"] }

application = { path = "../application" }
infrastructure = { path = "../infrastructure" }